backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/resources/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Image', name: 'image', widget: image, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Authors',
          name: 'authors',
          widget: 'list',
          field: { label: 'Author Name', name: 'name', widget: 'string' },
        }

  - label: 'Videos'
    name: 'videos'
    folder: 'src/pages/resources/videos'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'video-post' }
      - {
          label: 'Video URL',
          name: 'videoURL',
          widget: 'string',
          required: true,
          hint: '★ Enter video URL (e.g., YouTube, Vimeo) ★',
        }
      - { label: 'Featured Video', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Description', name: 'description', widget: 'text', required: false }
      - {
          label: 'Presentors',
          name: 'presentors',
          widget: 'list',
          field: { label: 'Presentor Name', name: 'name', widget: 'string' },
          required: false,
        }

  - label: 'Webinars'
    name: 'webinars'
    folder: 'src/pages/resources/webinars'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'webinar-post' }
      - {
          label: 'Video URL',
          name: 'videoURL',
          widget: 'string',
          required: true,
          hint: '★ Enter video URL (e.g., YouTube, Vimeo) ★',
        }
      - { label: 'Featured Video', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Description', name: 'description', widget: 'text', required: false }
      - {
          label: 'Presentors',
          name: 'presentors',
          widget: 'list',
          field: { label: 'Presentor Name', name: 'name', widget: 'string' },
          required: false,
        }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Homepage'
        name: 'index'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page' }
          - {
              label: Hero Section,
              name: hero,
              widget: object,
              fields:
                [
                  { label: Header, name: header, widget: string },
                  { label: Subtext, name: subtext, widget: string },
                ],
            }
          - {
              label: Who We Are Section,
              name: whoWeAre,
              widget: object,
              fields:
                [
                  { label: Header, name: header, widget: string },
                  { label: Subtext, name: subtext, widget: string },
                  { label: Body, name: body, widget: markdown },
                ],
            }
          - {
              label: Team Section,
              name: team,
              widget: object,
              fields:
                [
                  { label: Header, name: header, widget: string },
                  { label: Subtext, name: subtext, widget: string },
                  {
                    label: Team Members,
                    name: members,
                    widget: list,
                    fields:
                      [
                        { label: 'Member Name', name: 'name', widget: 'string' },
                        { label: 'Member Picture', name: 'pic', widget: 'image' },
                        { label: 'LinkedIn URL', name: 'linkedIn', widget: 'string' },
                        { label: 'Email', name: 'email', widget: 'string' },
                        { label: 'Member Position', name: 'position', widget: 'string' },
                        { label: 'Career Background', name: 'careerBackground', widget: 'text' },
                        { label: 'Specialities', name: 'specialities', widget: 'text' },
                        {
                          label: 'Industry Experience',
                          name: 'industryExperience',
                          widget: 'text',
                        },
                        { label: 'Certifications', name: 'certifications', widget: 'text' },
                        { label: 'Education', name: 'education', widget: 'text' },
                      ],
                  },
                ],
            }
          - {
              label: Core Values Section,
              name: coreValues,
              widget: object,
              fields:
                [
                  { label: Header, name: header, widget: string },
                  { label: Subtext, name: subtext, widget: string },
                  { label: Body, name: body, widget: markdown },
                  {
                    label: Values,
                    name: values,
                    widget: list,
                    fields:
                      [
                        { label: Name, name: name, widget: string },
                        { label: About, name: about, widget: text },
                        {
                          label: Reasons,
                          name: reasons,
                          widget: list,
                          fields:
                            [
                              { label: Reason, name: reason, widget: string },
                              { label: Explanation, name: explanation, widget: text },
                            ],
                        },
                      ],
                  },
                ],
            }
          - {
              label: Worked With Section,
              name: workedWith,
              widget: object,
              fields:
                [
                  { label: Header, name: header, widget: string },
                  { label: Subtext, name: subtext, widget: string },
                  {
                    label: Testimonials,
                    name: testimonials,
                    widget: list,
                    fields:
                      [
                        { label: Quote, name: quote, widget: text },
                        { label: Name, name: name, widget: string },
                        { label: Company, name: company, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Services Section,
              name: services,
              widget: object,
              fields:
                [
                  { label: Header, name: header, widget: string },
                  { label: Subtext, name: subtext, widget: string },
                  { label: Body, name: body, widget: markdown },
                  {
                    label: Services,
                    name: services,
                    widget: list,
                    fields:
                      [
                        { label: 'Service Name', name: 'name', widget: 'string' },
                        { label: 'Service Pitch', name: 'pitch', widget: 'string' },
                        { label: 'Service Description', name: 'description', widget: 'text' },
                      ],
                  },
                ],
            }
          - {
              label: Get Started Section,
              name: getStarted,
              widget: object,
              fields:
                [
                  { label: Header, name: header, widget: string },
                  { label: Subtext, name: subtext, widget: string },
                  {
                    label: Steps,
                    name: steps,
                    widget: list,
                    max: 3,
                    fields:
                      [
                        { label: 'Step Name', name: 'name', widget: 'string' },
                        { label: 'Step Explanation', name: 'explanation', widget: 'text' },
                      ],
                  },
                ],
            }
